---
# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "txt"

# Market names roughly ordered by likelyhood.
# Can contain market locations for fuzzy parsing

data:
  invoice_no:
     - Invoice No
     - Receipt No
     - Number
  invoice_date:
     - Invoice Date
  total:
     - Total
  due:
     - Due Date
     - Due
  sender:
     - From
     - Sender
  receiver:
     - To
     - Receiver

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - total
  - sum

sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'

# Matches dates like 19.08.15 and 19. 08. 2015
date_format: '.*?(?P<date>(\d{2,4}(\.\s?|[^a-zA-Z\d])\d{2}(\.\s?|[^a-zA-Z\d])(20)?1[3-6]))\s+'